# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeiraLivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nível_agregação', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('sigilo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
