# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feiralivre',
            options={'verbose_name': 'feira livre', 'verbose_name_plural': 'feiras livres'},
        ),
    ]
