# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170912_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feiralivre',
            name='nível_agregação',
        ),
        migrations.AddField(
            model_name='feiralivre',
            name='nivel_agregacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nível de Agregação'),
        ),
        migrations.AlterField(
            model_name='feiralivre',
            name='data_referencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Referência'),
        ),
        migrations.AlterField(
            model_name='feiralivre',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='feiralivre',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável'),
        ),
    ]
